const products = [
  {
    id: "1",
    title: "Aglaonema Silver Bay - Green type",
    type: "Green type",
    potSize: null,
    weight: null,
    height: null,
    colors: "Green",
    price: 4.5,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "2",
    title: "Anthurium - Bianco/Rosso/etc",
    type: "Bianco/Rosso/etc",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 15,
  },
  {
    id: "3",
    title: "Asparagus - Sprengeri",
    type: "Sprengeri",
    potSize: 20,
    weight: null,
    height: null,
    colors: "Green",
    price: 4.5,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 20,
  },
  {
    id: "4",
    title: "Araucaria heterophylla - Pino di Norfolk",
    type: "Pino di Norfolk",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 8,
  },
  {
    id: "5",
    title: "Aristolochia Littoralis",
    type: null,
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 5,
  },
  {
    id: "6",
    title: "Beaucarnea Guatemalensis - Green type",
    type: "Green type",
    potSize: "20 | 25 | 35",
    weight: null,
    height: null,
    colors: "Green",
    price: "8.4 | 16.0 | 35.0",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 30,
  },
  {
    id: "7",
    title: "Beaucarnea Recurvata - Green type",
    type: "Green type",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 12,
  },
  {
    id: "8",
    title: "Begonia",
    type: null,
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 20,
  },
  {
    id: "9",
    title: "Bougainvillea Alexandra - Albero",
    type: "Albero",
    potSize: "19 | 24",
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "10",
    title: "Bougainvillea Alexandra - Cespuglio",
    type: "Cespuglio",
    potSize: "14 | 17 | 21",
    weight: null,
    height: null,
    colors: null,
    price: "4.35 | 5.05 | 8.25",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 25,
  },
  {
    id: "11",
    title: "Bougainvillea Alexandra - Esemplare",
    type: "Esemplare",
    potSize: "30",
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 8,
  },
  {
    id: "12",
    title: "Bougainvillea Alexandra - Mezzo Fusto",
    type: "Mezzo Fusto",
    potSize: "17",
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 12,
  },
  {
    id: "13",
    title: "Bougainvillea Alexandra - Pyramide",
    type: "Pyramide",
    potSize: "19 | 24 | 30",
    weight: null,
    height: null,
    colors: null,
    price: "6.6 | 14.85 | 24.75",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 20,
  },
  {
    id: "14",
    title: "Bougainvillea Alexandra - Spalliera",
    type: "Spalliera",
    potSize: "17",
    weight: null,
    height: null,
    colors: null,
    price: 6.15,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 15,
  },
  {
    id: "15",
    title: "Bromelia Guzmania - Hope",
    type: "Hope",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 18,
  },
  {
    id: "16",
    title: "Bromelia Guzmania - Torch",
    type: "Torch",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "17",
    title: "Bromelia Guzmania - Vriesea",
    type: "Vriesea",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "18",
    title: "Calathea Makoyana",
    type: null,
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 20,
  },
  {
    id: "19",
    title: "Callistemon Splendens - Albero",
    type: "Albero",
    potSize: "19 | 21 | 24",
    weight: null,
    height: null,
    colors: "Green",
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 15,
  },
  {
    id: "20",
    title: "Callistemon Splendens - Cespuglio",
    type: "Cespuglio",
    potSize: "17 | 24",
    weight: null,
    height: null,
    colors: "Green",
    price: "8.25",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 12,
  },
  {
    id: "21",
    title: "Callistemon Splendens - Mezzo Fusto",
    type: "Mezzo Fusto",
    potSize: "17 | 21 | 24",
    weight: null,
    height: null,
    colors: "Green",
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "22",
    title: "CHAMAEDOREA ELEGANS - Green Type",
    type: "Green Type",
    potSize: "17 | 21",
    weight: null,
    height: null,
    colors: "Green",
    price: "4.95 | 6.5",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 25,
  },
  {
    id: "23",
    title: "Ciclamino - Cespuglio",
    type: "Cespuglio",
    potSize: "15",
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 30,
  },
  {
    id: "24",
    title: "Crassula Hobbit - Orecchie di Shrek",
    type: null,
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 20,
  },
  {
    id: "25",
    title: "Crassula Ovata - Albero di Giada",
    type: null,
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 15,
  },
  {
    id: "26",
    title: "Croton - Codiaeum Variegatum",
    type: null,
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 20,
  },
  {
    id: "27",
    title: "Cycas - Revoluta Palma Nana",
    type: null,
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 15,
  },
  {
    id: "28",
    title: "Cyclamen",
    type: null,
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "29",
    title: "Diamantina",
    type: null,
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 12,
  },
  {
    id: "30",
    title: "Echeveria",
    type: null,
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 15,
  },
  {
    id: "31",
    title: "Edera Helix - Elegantissima",
    type: "Green Type",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 25,
  },
  {
    id: "32",
    title: "Eucalyptus Gunnii - Baby Blue",
    type: "Baby Blue",
    potSize: "18",
    weight: null,
    height: null,
    colors: "Green",
    price: "5.5",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 30,
  },
  {
    id: "33",
    title: "Eucalyptus Gunnii - Piramide",
    type: "Piramide",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 20,
  },
  {
    id: "34",
    title: "Felce di Boston - Nephrolepis",
    type: "Nephrolepis",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 18,
  },
  {
    id: "35",
    title: "Ficus - Altissima 'Yellow Gem'",
    type: "Altissima 'Yellow Gem'",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "36",
    title: "Ficus - Australis",
    type: "Australis",
    potSize: "21",
    weight: null,
    height: null,
    colors: "Green",
    price: "7.5",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 15,
  },
  {
    id: "37",
    title: "Ficus - Benjamin Daniel",
    type: "Benjamin Daniel",
    potSize: "21",
    weight: null,
    height: null,
    colors: "Green",
    price: "8.25",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 12,
  },
  {
    id: "38",
    title: "Ficus - Ginseng Bonsai",
    type: "Ginseng Bonsai",
    potSize: "20 | 25",
    weight: "500gr | 750gr",
    height: null,
    colors: "Green",
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 8,
  },
  {
    id: "39",
    title: "Ficus - Microcarpa",
    type: "Microcarpa",
    potSize: "17 | 20 | 25 | 35",
    weight: null,
    height: null,
    colors: "Green",
    price: "5.5 | 8.4 | 16.0 | 30.0",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 25,
  },
  {
    id: "40",
    title: "Ficus - Microcarpa S-Shape",
    type: "Microcarpa S-Shape",
    potSize: "25 | 35 | 40",
    weight: null,
    height: null,
    colors: "Green",
    price: "22.0 | 41.0 | 50.0",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "41",
    title: "Ficus - Microcarpa Esemp.",
    type: "Microcarpa Esemp.",
    potSize: "40",
    weight: null,
    height: null,
    colors: "Green",
    price: "115.0",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 5,
  },
  {
    id: "42",
    title: "Hibiscus Rosa Sinensis - Cespuglio",
    type: "Cespuglio",
    potSize: "17",
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 20,
  },
  {
    id: "43",
    title: "Hydrangea - Ortensia",
    type: "Ortensia",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 18,
  },
  {
    id: "44",
    title: "Kentia Howea Forsteriana",
    type: "Kentia Howea Forsteriana",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 12,
  },
  {
    id: "45",
    title: "Mandevillea Alice Du Pont",
    type: "Mandevillea Alice Du Pont",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "46",
    title: "Monstera - Deliciosa",
    type: "Deliciosa",
    potSize: "21",
    weight: null,
    height: null,
    colors: "Green",
    price: "8.25",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 25,
  },
  {
    id: "47",
    title: "Monstera - Adansonii",
    type: "Adansonii",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 15,
  },
  {
    id: "48",
    title: "Olea Europaea M/F",
    type: "Olea Europaea M/F",
    potSize: "24",
    weight: null,
    height: null,
    colors: "Green",
    price: "15.0",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 12,
  },
  {
    id: "49",
    title: "Opuntia - Monacantha",
    type: "Monacantha",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "50",
    title: "Opuntia - Subulata Ago di Eva",
    type: "Subulata Ago di Eva",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 8,
  },
  {
    id: "51",
    title: "Ortensia - Cespuglio",
    type: "Cespuglio",
    potSize: "17 | 21",
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 15,
  },
  {
    id: "52",
    title: "Passiflora - Pyramide",
    type: "Pyramide",
    potSize: "17 | 24",
    weight: null,
    height: null,
    colors: "Mix",
    price: "6.15 | 14.85",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 20,
  },
  {
    id: "53",
    title: "Pachypodium Lamerei - Palma del Madagascar",
    type: "Palma del Madagascar",
    potSize: "20",
    weight: null,
    height: null,
    colors: "Green",
    price: "4.5",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "54",
    title: "Palma Areca - Dypsis Lutescens",
    type: "Dypsis Lutescens",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 12,
  },
  {
    id: "55",
    title: "Phoenix Canariensis - Palma delle Canarie",
    type: "Palma delle Canarie",
    potSize: "12 | 14",
    weight: null,
    height: null,
    colors: "Green",
    price: "1.5 | 2.3",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 18,
  },
  {
    id: "56",
    title: "Philodendron - Birkin Zebra",
    type: "Birkin Zebra",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 15,
  },
  {
    id: "57",
    title: "Philodendron - Scandens Brazil",
    type: "Scandens Brazil",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 15,
  },
  {
    id: "58",
    title: "Pothos - Green type",
    type: "Green type",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 20,
  },
  {
    id: "59",
    title: "Pothos con tutore - Green type",
    type: "Green type",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 18,
  },
  {
    id: "60",
    title: "Portulacaria Afra - Pianta dell’elefante",
    type: "Pianta dell’elefante",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 12,
  },
  {
    id: "61",
    title: "Portulacaria Afra - Cespuglio d’elefante",
    type: "Cespuglio d’elefante",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "62",
    title: "Rosa - Pyramide",
    type: "Pyramide",
    potSize: "21",
    weight: null,
    height: null,
    colors: "Red, White, Yellow",
    price: "7.00",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 25,
  },
  {
    id: "63",
    title: "Rosa - Mezzo Fusto",
    type: "Mezzo Fusto",
    potSize: "17",
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 15,
  },
  {
    id: "64",
    title: "Rosa - Multiflora Albero",
    type: "Multiflora Albero",
    potSize: "21",
    weight: null,
    height: null,
    colors: "Red, White, Yellow",
    price: "7.00",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 20,
  },
  {
    id: "65",
    title: "Sansevieria Laurentii - n. 8 foglie",
    type: "n. 8 foglie",
    potSize: "17",
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "66",
    title: "Sansevieria Laurentii - n. 9 foglie",
    type: "n. 9 foglie",
    potSize: "19",
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 8,
  },
  {
    id: "67",
    title: "Sansevieria Laurentii - n. 27 foglie",
    type: "n. 27 foglie",
    potSize: "24",
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 6,
  },
  {
    id: "68",
    title: "Sansevieria Futura Superba - Lingua di Suocera",
    type: "Lingua di Suocera",
    potSize: "19",
    weight: null,
    height: null,
    colors: "Green",
    price: "8.00",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 12,
  },
  {
    id: "69",
    title: "Schefflera Actinophylla Amate - Green type",
    type: "Green type",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 18,
  },
  {
    id: "70",
    title: "Scindapsus - ",
    type: null,
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 20,
  },
  {
    id: "71",
    title: "Sedum Morganianum Burrito - coda d’asino",
    type: "coda d’asino",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 15,
  },
  {
    id: "72",
    title: "Spathiphyllum - Bianco",
    type: "Bianco",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 20,
  },
  {
    id: "73",
    title: "Strelitzia - Nicolai",
    type: "Nicolai",
    potSize: "24 | 30",
    weight: null,
    height: null,
    colors: "Green",
    price: "13.75 | 24.20",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 25,
  },
  {
    id: "74",
    title: "Strelitzia - Reginae",
    type: "Reginae",
    potSize: "17 | 24",
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "75",
    title: "Strelitzia - Augusta",
    type: "Augusta",
    potSize: "21 | 24 | 30 | 40",
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 8,
  },
  {
    id: "76",
    title: "Sundavillea - Cespuglio",
    type: "Cespuglio",
    potSize: "10.5 | 14 | 17",
    weight: null,
    height: null,
    colors: "Mix",
    price: "2.05 | 3.2 | 5.05",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 30,
  },
  {
    id: "77",
    title: "Sundavillea - Pyramide",
    type: "Pyramide",
    potSize: "17 | 19 | 21",
    weight: null,
    height: null,
    colors: "Mix",
    price: "6.15 | 6.6 | 11",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 18,
  },
  {
    id: "78",
    title: "Sundavillea - Basket",
    type: "Basket",
    potSize: "18",
    weight: null,
    height: null,
    colors: "Mix | Tricolore",
    price: "6.6 | 7.15",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "79",
    title: "Sundavillea - Spalliera",
    type: "Spalliera",
    potSize: "19",
    weight: null,
    height: null,
    colors: "Mix",
    price: "7.15",
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 12,
  },
  {
    id: "80",
    title: "Trachycarpus Fortunei - ",
    type: null,
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 15,
  },
  {
    id: "81",
    title: "Tillandsia - Pianta dell’aria",
    type: "Pianta dell’aria",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 20,
  },
  {
    id: "82",
    title: "Ulivo Olea Europaea - Green type",
    type: "Green type",
    potSize: null,
    weight: null,
    height: null,
    colors: "Green",
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 18,
  },
  {
    id: "83",
    title: "Zantedeschia Albomaculata - Colors",
    type: "Colors",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 10,
  },
  {
    id: "84",
    title: "Zamioculcas Zamilifolia",
    type: null,
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 12,
  },
  {
    id: "85",
    title: "Philodendron - Scandens Brazil",
    type: "Scandens Brazil",
    potSize: null,
    weight: null,
    height: null,
    colors: null,
    price: null,
    imageUrl: "URL_DE_LA_IMAGEN",
    stock: 15,
  },
];

export default products;
